In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          608     Spain  Female  41.0   
2          3    15619304      Onio          502    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1        1.0             1.0   
1       1   83807.86              1        0.0             1.0   
2       8  159660.80              3        1.0             0.0   
3       1       0.00              2        0.0             0.0   
4       2  125510.82              1        NaN             1.0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10002 non-null  int64  
 1   CustomerId       10002 non-null  int64  
 2   Surname          10002 non-null  object 
 3   CreditScore      10002 non-null  int64  
 4   Geography        10001 non-null  object 
 5   Gender           10002 non-null  object 
 6   Age              10001 non-null  float64
 7   Tenure           10002 non-null  int64  
 8   Balance          10002 non-null  float64
 9   NumOfProducts    10002 non-null  int64  
 10  HasCrCard        10001 non-null  float64
 11  IsActiveMember   10001 non-null  float64
 12  EstimatedSalary  10002 non-null  float64
 13  Exited           10002 non-null  int64  
dtypes: float64(5), int64(6), object(3)
memory usage: 1.1+ MB


In [4]:
df.shape

(10002, 14)

In [5]:
df.size

140028

In [6]:
df.drop(['RowNumber','CustomerId','Surname'], axis = 'columns', inplace =True)

In [7]:
df.head()

CreditScore Geography  Gender   Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female  42.0       2       0.00              1   
1          608     Spain  Female  41.0       1   83807.86              1   
2          502    France  Female  42.0       8  159660.80              3   
3          699    France  Female  39.0       1       0.00              2   
4          850     Spain  Female  43.0       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0        1.0             1.0        101348.88       1  
1        0.0             1.0        112542.58       0  
2        1.0             0.0        113931.57       1  
3        0.0             0.0         93826.63       0  
4        NaN             1.0         79084.10       0

In [8]:
df.isnull().sum()

CreditScore        0
Geography          1
Gender             0
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          1
IsActiveMember     1
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
df.dropna(inplace = True)

In [10]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
df.duplicated().sum()

2

In [12]:
df.drop_duplicates(inplace = True)

In [13]:
df.duplicated().sum()

0

In [14]:
df.describe()

CreditScore          Age       Tenure        Balance  NumOfProducts  \
count  9996.000000  9996.000000  9996.000000    9996.000000    9996.000000   
mean    650.503301    38.921071     5.013305   76476.263216       1.530212   
std      96.624668    10.488421     2.892353   62397.118820       0.581684   
min     350.000000    18.000000     0.000000       0.000000       1.000000   
25%     584.000000    32.000000     3.000000       0.000000       1.000000   
50%     652.000000    37.000000     5.000000   97173.290000       1.000000   
75%     717.250000    44.000000     7.250000  127639.372500       2.000000   
max     850.000000    92.000000    10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary       Exited  
count  9996.000000     9996.000000      9996.000000  9996.000000  
mean      0.705482        0.514906    100106.701248     0.203782  
std       0.455849        0.499803     57513.314398     0.402829  
min       0.000000        0.000000        11.580000     0.000000  
25%       0.000000        0.000000     51002.110000     0.000000  
50%       1.000000        1.000000    100238.110000     0.000000  
75%       1.000000        1.000000    149400.107500     0.000000  
max       1.000000        1.000000    199992.480000     1.000000

In [15]:
df.sample(5)

CreditScore Geography  Gender   Age  Tenure    Balance  NumOfProducts  \
9520          727   Germany  Female  18.0       2   93816.70              2   
5460          661   Germany    Male  41.0       5  122552.48              2   
7628          850    France    Male  28.0       8   99986.98              1   
4340          577     Spain  Female  44.0       8  115557.00              1   
8401          535     Spain    Male  58.0       1       0.00              2   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
9520        1.0             0.0        126172.11       0  
5460        0.0             1.0        120646.40       0  
7628        1.0             0.0        196582.55       0  
4340        0.0             1.0        127506.76       0  
8401        1.0             1.0         11779.98       1

In [16]:
df_cat = df.select_dtypes('object')
df_num = df.select_dtypes(include = ['int','float'])

In [17]:
df_cat.head()

Geography  Gender
0    France  Female
1     Spain  Female
2    France  Female
3    France  Female
5     Spain    Male

In [18]:
df_num.head()

CreditScore   Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619  42.0       2       0.00              1        1.0   
1          608  41.0       1   83807.86              1        0.0   
2          502  42.0       8  159660.80              3        1.0   
3          699  39.0       1       0.00              2        0.0   
5          645  44.0       8  113755.78              2        1.0   

   IsActiveMember  EstimatedSalary  Exited  
0             1.0        101348.88       1  
1             1.0        112542.58       0  
2             0.0        113931.57       1  
3             0.0         93826.63       0  
5             0.0        149756.71       1

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
for col in df_cat:
    le = LabelEncoder()
    df_cat[col] = le.fit_transform(df_cat[col])

In [21]:
df_cat

Geography  Gender
0              0       0
1              2       0
2              0       0
3              0       0
5              2       1
...          ...     ...
9995           0       1
9996           0       1
9997           0       0
9998           1       1
10000          0       0

[9996 rows x 2 columns]

In [22]:
df = pd.concat([df_cat,df_num],axis = 1)

In [23]:
df.head()

Geography  Gender  CreditScore   Age  Tenure    Balance  NumOfProducts  \
0          0       0          619  42.0       2       0.00              1   
1          2       0          608  41.0       1   83807.86              1   
2          0       0          502  42.0       8  159660.80              3   
3          0       0          699  39.0       1       0.00              2   
5          2       1          645  44.0       8  113755.78              2   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0        1.0             1.0        101348.88       1  
1        0.0             1.0        112542.58       0  
2        1.0             0.0        113931.57       1  
3        0.0             0.0         93826.63       0  
5        1.0             0.0        149756.71       1

In [24]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [25]:
x.head()

Geography  Gender  CreditScore   Age  Tenure    Balance  NumOfProducts  \
0          0       0          619  42.0       2       0.00              1   
1          2       0          608  41.0       1   83807.86              1   
2          0       0          502  42.0       8  159660.80              3   
3          0       0          699  39.0       1       0.00              2   
5          2       1          645  44.0       8  113755.78              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0        1.0             1.0        101348.88  
1        0.0             1.0        112542.58  
2        1.0             0.0        113931.57  
3        0.0             0.0         93826.63  
5        1.0             0.0        149756.71

In [26]:
y.head()

0    1
1    0
2    1
3    0
5    1
Name: Exited, dtype: int64

In [27]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.25,random_state = 1)

In [28]:
def build_models(model):
    model.fit(xtrain,ytrain)
    ypred = model.predict(xtest)
    print(confusion_matrix(ytest,ypred))
    print(classification_report(ytest,ypred))
    print('Training Score : ',model.score(xtrain,ytrain))
    print('Testing Score : ',model.score(xtest,ytest))

In [29]:
lr = LogisticRegression()
knn = KNeighborsClassifier()
svm = SVC()
dt = DecisionTreeClassifier()

In [30]:
build_models(lr)

[[1935   36]
 [ 502   26]]
              precision    recall  f1-score   support

           0       0.79      0.98      0.88      1971
           1       0.42      0.05      0.09       528

    accuracy                           0.78      2499
   macro avg       0.61      0.52      0.48      2499
weighted avg       0.71      0.78      0.71      2499

Training Score :  0.7933840202747766
Testing Score :  0.7847138855542217


In [31]:
lr = LogisticRegression(penalty = 'l2',solver = 'liblinear')
build_models(lr)

[[1930   41]
 [ 497   31]]
              precision    recall  f1-score   support

           0       0.80      0.98      0.88      1971
           1       0.43      0.06      0.10       528

    accuracy                           0.78      2499
   macro avg       0.61      0.52      0.49      2499
weighted avg       0.72      0.78      0.71      2499

Training Score :  0.7923169267707083
Testing Score :  0.7847138855542217


In [32]:
lr = LogisticRegression(penalty = 'l2',solver = 'sag')
build_models(lr)

[[1971    0]
 [ 528    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.00      0.00      0.00       528

    accuracy                           0.79      2499
   macro avg       0.39      0.50      0.44      2499
weighted avg       0.62      0.79      0.70      2499

Training Score :  0.798719487795118
Testing Score :  0.7887154861944778


In [33]:
lr = LogisticRegression(penalty = 'l2',solver = 'saga')
build_models(lr)

[[1971    0]
 [ 528    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.00      0.00      0.00       528

    accuracy                           0.79      2499
   macro avg       0.39      0.50      0.44      2499
weighted avg       0.62      0.79      0.70      2499

Training Score :  0.798719487795118
Testing Score :  0.7887154861944778


In [34]:
lr = LogisticRegression(penalty = 'l1',solver = 'liblinear')
build_models(lr)

[[1920   51]
 [ 444   84]]
              precision    recall  f1-score   support

           0       0.81      0.97      0.89      1971
           1       0.62      0.16      0.25       528

    accuracy                           0.80      2499
   macro avg       0.72      0.57      0.57      2499
weighted avg       0.77      0.80      0.75      2499

Training Score :  0.8107242897158864
Testing Score :  0.801920768307323


In [35]:
lr = LogisticRegression(penalty = 'l1',solver = 'saga')
build_models(lr)

[[1971    0]
 [ 528    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.00      0.00      0.00       528

    accuracy                           0.79      2499
   macro avg       0.39      0.50      0.44      2499
weighted avg       0.62      0.79      0.70      2499

Training Score :  0.798719487795118
Testing Score :  0.7887154861944778


In [36]:
lr = LogisticRegression(penalty = 'l1',solver = 'liblinear')
build_models(lr)

[[1919   52]
 [ 442   86]]
              precision    recall  f1-score   support

           0       0.81      0.97      0.89      1971
           1       0.62      0.16      0.26       528

    accuracy                           0.80      2499
   macro avg       0.72      0.57      0.57      2499
weighted avg       0.77      0.80      0.75      2499

Training Score :  0.811391223155929
Testing Score :  0.8023209283713485


In [37]:
# Sensitivity
# TPR = TP / (FN + TP)
TPR = 86 / (52 + 86)
TPR

0.6231884057971014

In [38]:
# Specificity
# TNR = TN / (FP + TN)
TNR = 1919 / (442 + 1919)
TNR

0.8127911901736552

In [39]:
build_models(knn)

[[1835  136]
 [ 479   49]]
              precision    recall  f1-score   support

           0       0.79      0.93      0.86      1971
           1       0.26      0.09      0.14       528

    accuracy                           0.75      2499
   macro avg       0.53      0.51      0.50      2499
weighted avg       0.68      0.75      0.70      2499

Training Score :  0.8184607176203815
Testing Score :  0.7539015606242497


In [40]:
for i in range(1,31):
    knn = KNeighborsClassifier(n_neighbors = i)
    print(i)
    build_models(knn)

1
[[1569  402]
 [ 400  128]]
              precision    recall  f1-score   support

           0       0.80      0.80      0.80      1971
           1       0.24      0.24      0.24       528

    accuracy                           0.68      2499
   macro avg       0.52      0.52      0.52      2499
weighted avg       0.68      0.68      0.68      2499

Training Score :  1.0
Testing Score :  0.6790716286514605
2
[[1873   98]
 [ 505   23]]
              precision    recall  f1-score   support

           0       0.79      0.95      0.86      1971
           1       0.19      0.04      0.07       528

    accuracy                           0.76      2499
   macro avg       0.49      0.50      0.47      2499
weighted avg       0.66      0.76      0.69      2499

Training Score :  0.8408696812058156
Testing Score :  0.758703481392557
3
[[1717  254]
 [ 465   63]]
              precision    recall  f1-score   support

           0       0.79      0.87      0.83      1971
           1       0

In [41]:
knn = KNeighborsClassifier(n_neighbors = 2)
build_models(knn)

[[1873   98]
 [ 505   23]]
              precision    recall  f1-score   support

           0       0.79      0.95      0.86      1971
           1       0.19      0.04      0.07       528

    accuracy                           0.76      2499
   macro avg       0.49      0.50      0.47      2499
weighted avg       0.66      0.76      0.69      2499

Training Score :  0.8408696812058156
Testing Score :  0.758703481392557


In [42]:
# Sensitivity
# TPR = TP / (FN + TP)
TPR = 98 / (23 + 98)
TPR

0.8099173553719008

In [43]:
# Specificity
# TNR = TN / (FP + TN)
TNR = 1873 / (505 + 1873)
TNR

0.787636669470143

In [44]:
build_models(svm)

[[1971    0]
 [ 528    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.00      0.00      0.00       528

    accuracy                           0.79      2499
   macro avg       0.39      0.50      0.44      2499
weighted avg       0.62      0.79      0.70      2499

Training Score :  0.798719487795118
Testing Score :  0.7887154861944778


In [45]:
svm = SVC(kernel = 'sigmoid')
build_models(svm)

[[1574  397]
 [ 438   90]]
              precision    recall  f1-score   support

           0       0.78      0.80      0.79      1971
           1       0.18      0.17      0.18       528

    accuracy                           0.67      2499
   macro avg       0.48      0.48      0.48      2499
weighted avg       0.66      0.67      0.66      2499

Training Score :  0.6834733893557423
Testing Score :  0.6658663465386154


In [46]:
svm = SVC(kernel = 'poly')
build_models(svm)

[[1971    0]
 [ 528    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.00      0.00      0.00       528

    accuracy                           0.79      2499
   macro avg       0.39      0.50      0.44      2499
weighted avg       0.62      0.79      0.70      2499

Training Score :  0.798719487795118
Testing Score :  0.7887154861944778


In [47]:
svm = SVC(kernel = 'linear')
build_models(svm)

[[1930   41]
 [ 515   13]]
              precision    recall  f1-score   support

           0       0.79      0.98      0.87      1971
           1       0.24      0.02      0.04       528

    accuracy                           0.78      2499
   macro avg       0.52      0.50      0.46      2499
weighted avg       0.67      0.78      0.70      2499

Training Score :  0.7856475923702815
Testing Score :  0.7775110044017607


In [48]:
# Sensitivity
# TPR = TP / (FN + TP)
TPR = 13 / (41 + 13)
TPR

0.24074074074074073

In [49]:
# Specificity
# TNR = TN / (FP + TN)
TNR = 1930 / (515 + 1930)
TNR

0.7893660531697342

In [50]:
build_models(dt)

[[1714  257]
 [ 256  272]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87      1971
           1       0.51      0.52      0.51       528

    accuracy                           0.79      2499
   macro avg       0.69      0.69      0.69      2499
weighted avg       0.79      0.79      0.79      2499

Training Score :  1.0
Testing Score :  0.7947178871548619


In [51]:
for i in range(1,31):
    dt1 = DecisionTreeClassifier(max_depth = i)
    dt1.fit(xtrain,ytrain)
    yp = dt1.predict(xtest)
    ac = accuracy_score(ytest,yp)
    print(f'max depth : {i} , Accuracy Score {ac}')

max depth : 1 , Accuracy Score 0.7887154861944778
max depth : 2 , Accuracy Score 0.8303321328531412
max depth : 3 , Accuracy Score 0.8323329331732693
max depth : 4 , Accuracy Score 0.8419367747098839
max depth : 5 , Accuracy Score 0.8499399759903962
max depth : 6 , Accuracy Score 0.84593837535014
max depth : 7 , Accuracy Score 0.851140456182473
max depth : 8 , Accuracy Score 0.8519407763105242
max depth : 9 , Accuracy Score 0.8419367747098839
max depth : 10 , Accuracy Score 0.8359343737494997
max depth : 11 , Accuracy Score 0.8291316526610645
max depth : 12 , Accuracy Score 0.8239295718287315
max depth : 13 , Accuracy Score 0.8099239695878351
max depth : 14 , Accuracy Score 0.8115246098439376
max depth : 15 , Accuracy Score 0.7995198079231692
max depth : 16 , Accuracy Score 0.7975190076030412
max depth : 17 , Accuracy Score 0.7927170868347339
max depth : 18 , Accuracy Score 0.7939175670268107
max depth : 19 , Accuracy Score 0.8027210884353742
max depth : 20 , Accuracy Score 0.797118847

In [52]:
dt2 = DecisionTreeClassifier(max_depth = 8)
build_models(dt2)

[[1883   88]
 [ 278  250]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1971
           1       0.74      0.47      0.58       528

    accuracy                           0.85      2499
   macro avg       0.81      0.71      0.74      2499
weighted avg       0.84      0.85      0.84      2499

Training Score :  0.879951980792317
Testing Score :  0.8535414165666266


In [53]:
for i in range(2,101):
    dt1 = DecisionTreeClassifier(min_samples_split = i)
    dt1.fit(xtrain,ytrain)
    yp = dt1.predict(xtest)
    ac = accuracy_score(ytest,yp)
    print(f'max depth : {i} , Accuracy Score {ac}')

max depth : 2 , Accuracy Score 0.7899159663865546
max depth : 3 , Accuracy Score 0.7995198079231692
max depth : 4 , Accuracy Score 0.8015206082432973
max depth : 5 , Accuracy Score 0.8043217286914766
max depth : 6 , Accuracy Score 0.8059223689475791
max depth : 7 , Accuracy Score 0.8071228491396558
max depth : 8 , Accuracy Score 0.8095238095238095
max depth : 9 , Accuracy Score 0.8059223689475791
max depth : 10 , Accuracy Score 0.8079231692677071
max depth : 11 , Accuracy Score 0.8107242897158864
max depth : 12 , Accuracy Score 0.8135254101640657
max depth : 13 , Accuracy Score 0.8135254101640657
max depth : 14 , Accuracy Score 0.8167266906762705
max depth : 15 , Accuracy Score 0.8187274909963985
max depth : 16 , Accuracy Score 0.8211284513805522
max depth : 17 , Accuracy Score 0.8235294117647058
max depth : 18 , Accuracy Score 0.8259303721488596
max depth : 19 , Accuracy Score 0.8247298919567827
max depth : 20 , Accuracy Score 0.8263305322128851
max depth : 21 , Accuracy Score 0.82593

In [54]:
dt3 = DecisionTreeClassifier(min_samples_split = 72)
build_models(dt3)

[[1886   85]
 [ 279  249]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1971
           1       0.75      0.47      0.58       528

    accuracy                           0.85      2499
   macro avg       0.81      0.71      0.74      2499
weighted avg       0.84      0.85      0.84      2499

Training Score :  0.8779511804721889
Testing Score :  0.8543417366946778


In [55]:
for i in range(1,101):
    dt1 = DecisionTreeClassifier(min_samples_leaf = i)
    dt1.fit(xtrain,ytrain)
    yp = dt1.predict(xtest)
    ac = accuracy_score(ytest,yp)
    print(f'max depth : {i} , Accuracy Score {ac}')

max depth : 1 , Accuracy Score 0.8003201280512204
max depth : 2 , Accuracy Score 0.8227290916366546
max depth : 3 , Accuracy Score 0.8115246098439376
max depth : 4 , Accuracy Score 0.8235294117647058
max depth : 5 , Accuracy Score 0.8235294117647058
max depth : 6 , Accuracy Score 0.8331332533013205
max depth : 7 , Accuracy Score 0.8335334133653461
max depth : 8 , Accuracy Score 0.8383353341336535
max depth : 9 , Accuracy Score 0.8359343737494997
max depth : 10 , Accuracy Score 0.8407362945178071
max depth : 11 , Accuracy Score 0.8411364545818327
max depth : 12 , Accuracy Score 0.843937575030012
max depth : 13 , Accuracy Score 0.8463385354141657
max depth : 14 , Accuracy Score 0.8495398159263705
max depth : 15 , Accuracy Score 0.8479391756702681
max depth : 16 , Accuracy Score 0.8427370948379351
max depth : 17 , Accuracy Score 0.8403361344537815
max depth : 18 , Accuracy Score 0.8387354941976791
max depth : 19 , Accuracy Score 0.8403361344537815
max depth : 20 , Accuracy Score 0.8407362

In [56]:
dt4 = DecisionTreeClassifier(min_samples_leaf = 36)
build_models(dt4)

[[1892   79]
 [ 302  226]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      1971
           1       0.74      0.43      0.54       528

    accuracy                           0.85      2499
   macro avg       0.80      0.69      0.73      2499
weighted avg       0.84      0.85      0.83      2499

Training Score :  0.861811391223156
Testing Score :  0.8475390156062425


In [57]:
dt3 = DecisionTreeClassifier(min_samples_split = 72)
build_models(dt3)

[[1886   85]
 [ 279  249]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1971
           1       0.75      0.47      0.58       528

    accuracy                           0.85      2499
   macro avg       0.81      0.71      0.74      2499
weighted avg       0.84      0.85      0.84      2499

Training Score :  0.8779511804721889
Testing Score :  0.8543417366946778


In [58]:
# Sensitivity
# TPR = TP / (FN + TP)
TPR = 249 / (85 + 249)
TPR

0.7455089820359282

In [59]:
# Specificity
# TNR = TN / (FP + TN)
TNR = 1886 / (279 + 1886)
TNR

0.8711316397228638

In [60]:
!pip install xgboost

                                              0.0/99.8 MB ? eta -:--:--
                                              0.0/99.8 MB ? eta -:--:--
                                             0.1/99.8 MB 812.7 kB/s eta 0:02:03
                                             0.1/99.8 MB 812.7 kB/s eta 0:02:03
                                             0.1/99.8 MB 459.5 kB/s eta 0:03:37
                                             0.1/99.8 MB 459.5 kB/s eta 0:03:37
                                             0.1/99.8 MB 479.3 kB/s eta 0:03:28
                                             0.1/99.8 MB 500.5 kB/s eta 0:03:20
                                             0.1/99.8 MB 500.5 kB/s eta 0:03:20
                                             0.2/99.8 MB 409.6 kB/s eta 0:04:04
                                             0.2/99.8 MB 409.6 kB/s eta 0:04:04
                                             0.2/99.8 MB 491.0 kB/s eta 0:03:23
                                             0.3/99.8 MB


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [61]:
from sklearn.ensemble import BaggingClassifier,RandomForestClassifier,VotingClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier

#### Bagging and RandomForest 

In [70]:
def BuildBCRFModels(model):
    model.fit(xtrain,ytrain)
    ypred = model.predict(xtest)
    print(confusion_matrix(ytest,ypred))
    print(classification_report(ytest,ypred))
    print(f'Training Score: {model.score(xtrain,ytrain)}')
    print(f'Testing Score: {model.score(xtest,ytest)}')

In [68]:
BClr = BaggingClassifier(LogisticRegression())
BCknn = BaggingClassifier(KNeighborsClassifier())
BCsvm = BaggingClassifier(SVC())
BCdt = BaggingClassifier(DecisionTreeClassifier())
rf = RandomForestClassifier()

In [71]:
BuildBCRFModels(BClr)

[[1963    8]
 [ 521    7]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.47      0.01      0.03       528

    accuracy                           0.79      2499
   macro avg       0.63      0.50      0.45      2499
weighted avg       0.72      0.79      0.70      2499

Training Score: 0.7957849806589302
Testing Score: 0.7883153261304522


In [72]:
BuildBCRFModels(BCknn)

[[1856  115]
 [ 493   35]]
              precision    recall  f1-score   support

           0       0.79      0.94      0.86      1971
           1       0.23      0.07      0.10       528

    accuracy                           0.76      2499
   macro avg       0.51      0.50      0.48      2499
weighted avg       0.67      0.76      0.70      2499

Training Score: 0.8215286114445778
Testing Score: 0.756702681072429


In [73]:
BuildBCRFModels(BCsvm)

[[1971    0]
 [ 528    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.00      0.00      0.00       528

    accuracy                           0.79      2499
   macro avg       0.39      0.50      0.44      2499
weighted avg       0.62      0.79      0.70      2499

Training Score: 0.798719487795118
Testing Score: 0.7887154861944778


In [74]:
BuildBCRFModels(BCdt)

[[1889   82]
 [ 290  238]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1971
           1       0.74      0.45      0.56       528

    accuracy                           0.85      2499
   macro avg       0.81      0.70      0.74      2499
weighted avg       0.84      0.85      0.84      2499

Training Score: 0.9837268240629585
Testing Score: 0.851140456182473


In [75]:
# Overfitting Scenario
BuildBCRFModels(rf)

[[1900   71]
 [ 294  234]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1971
           1       0.77      0.44      0.56       528

    accuracy                           0.85      2499
   macro avg       0.82      0.70      0.74      2499
weighted avg       0.85      0.85      0.84      2499

Training Score: 1.0
Testing Score: 0.8539415766306523


#### VotingClassifier

In [76]:
m1 = []
m1.append(('logistic regression',LogisticRegression()))
m1.append(('KNN',KNeighborsClassifier()))
m1.append(('SVM',SVC()))
m1.append(('decision tree',DecisionTreeClassifier()))

In [78]:
vc = VotingClassifier(estimators = m1)
vc.fit(xtrain,ytrain)
ypred = vc.predict(xtest)
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
print(f'training score : {vc.score(xtrain,ytrain)}')
print(f'testing score : {vc.score(xtest,ytest)}')

[[1970    1]
 [ 526    2]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1971
           1       0.67      0.00      0.01       528

    accuracy                           0.79      2499
   macro avg       0.73      0.50      0.44      2499
weighted avg       0.76      0.79      0.70      2499

training score : 0.8015206082432973
testing score : 0.7891156462585034


#### Boosting

In [79]:
def Buildboostmodels(models):
    models.fit(xtrain,ytrain)
    ypred = models.predict(xtest)
    print(confusion_matrix(ytest,ypred))
    print(classification_report(ytest,ypred))
    print(f'Training Score: {models.score(xtrain,ytrain)}')
    print(f'Testing Score: {models.score(xtest,ytest)}')

In [80]:
ada = AdaBoostClassifier()
gd = GradientBoostingClassifier()
xgd = XGBClassifier()

In [81]:
Buildboostmodels(ada)

[[1901   70]
 [ 291  237]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1971
           1       0.77      0.45      0.57       528

    accuracy                           0.86      2499
   macro avg       0.82      0.71      0.74      2499
weighted avg       0.85      0.86      0.84      2499

Training Score: 0.8588768840869682
Testing Score: 0.8555422168867547


In [82]:
Buildboostmodels(gd)

[[1919   52]
 [ 297  231]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1971
           1       0.82      0.44      0.57       528

    accuracy                           0.86      2499
   macro avg       0.84      0.71      0.74      2499
weighted avg       0.86      0.86      0.84      2499

Training Score: 0.8743497398959584
Testing Score: 0.860344137655062


In [83]:
Buildboostmodels(xgd)

[[1872   99]
 [ 275  253]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      1971
           1       0.72      0.48      0.57       528

    accuracy                           0.85      2499
   macro avg       0.80      0.71      0.74      2499
weighted avg       0.84      0.85      0.84      2499

Training Score: 0.9638522075496866
Testing Score: 0.8503401360544217
